#pragma once

#define MAX_FILENAME 30
#define MAX_FILEPATH 100
#define MAX_PARSERS_COUNT 100
#define MAX_SYSTEM_PATH 100
#define MAX_MESSAGE_LENGTH 200
#define MAX_DATA_HANDLERS 10
#define DATETIME_LENGTH 20
#define TIMESTAMP_LENGTH 11
